import styles from './page.module.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin Panel',
  description: 'Generated by create next app',
}

export default function AdminLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <main className={styles.main}>
        <div className={styles.nav}>
        <ul>
          <li><a href="/admin/sales">Sales</a></li>
          <li><a href="/admin/traffic">Traffic</a></li>
          <li><a href="/">Log Out</a></li>
        </ul>
        </div>
        {children}
      </main>
    )
  }